-- plugin
require("plugin.trouble")
require("plugin.diffview")
require("plugin.gitblame")
require("plugin.mkdp")
require("plugin.neoscroll")
require("plugin.lastplace")
require("plugin.surround")
require("plugin.repeat")
require("plugin.todocomments")
require("plugin.numb")
-- require("plugin.leap")
-- require("plugin.flit")
require("plugin.flash")
require("plugin.lspsignature")
require("plugin.colorscheme")
require("plugin.copyright")
